# Generated by Django 3.1.3 on 2020-11-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201105_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.SlugField(default='test-product'),
            preserve_default=False,
        ),
    ]
