# Generated by Django 3.1.3 on 2020-11-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='url',
            new_name='slug',
        ),
    ]
