# Generated by Django 3.1.3 on 2020-11-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discriptions',
            field=models.TextField(default='discript'),
            preserve_default=False,
        ),
    ]
