# Generated by Django 3.1.3 on 2020-11-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201119_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('discriptions', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='clothes/', verbose_name='Постер')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('pub_data', models.DateField(default='date.today', verbose_name='Дата публикации')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
